layout: avoid panic due to subtract with overflow
This can occur when 2 Press/Release attached to an HoldTap action are
handled between 2 ticks.

```
ERROR panicked at /home/boris/stuff/kb/keyberon/src/layout.rs:319:32:
attempt to subtract with overflow
```